ChainTest/ChainTest/urls.py
from django.contrib import admin
from django.urls import include,path

from ChainTest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('task_create', views.form_handle, name='form_handle')
]

ChainTest/ChainTest/models.py
from django.db import models, transaction
from django.db.models import F

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    name = models.CharField(max_length=100)
    priority = models.IntegerField('Priorytet')
    sendDate = models.DateField('Data wysyłki')

    def __str__(self):
        return self.name

class Technology(models.Model):
    name = models.CharField(max_length=100)


class TaskManager(models.Manager):
    def create_task(self, name, order):
        task = self.create(name=name, order=order)

    def move(self, task, new_number):
        qs = self.get_queryset()

        '''transaction.atomic sprawia, że do skończenia operacji nie zostaną dokonane żadne zmiany w bazie danych
        oznacza to, że dopiero na samym końcu będą zapisane, na ostatnim kroku '''
        with transaction.atomic():
            if task.number_ordering > int(new_number):
                qs.filter(
                    order = task.order,
                    number_ordering__lt = task.number_ordering,
                    number_ordering__gte = new_number
                ).exclude(
                    pk = task.pk
                ).update(
                    number_ordering = F('number_ordering') + 1,
                )
            else:
                qs.filter(
                    order = task.order,
                    number_ordering__lte = new_number,
                    number_ordering__gte = task.number_ordering
                ).exclude(
                    pk = task.pk
                ).update(
                    number_ordering = F('number_ordering') - 1,
                )
            
            task.number_ordering = new_number
            task.save()
            
            
class Task(models.Model):
    name = models.CharField(max_length=100)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    objects = TaskManager()
    number_ordering = models.IntegerField(default=1)

    def __str__(self):
        return self.name + ': ' + self.order.name

    class Meta:
        unique_together = ('order', 'name', )

ChainTest/ChainTest/forms.py
from django import forms
from ChainTest.models import Person, City, Country

class PersonForm(forms.ModelForm):
   class Meta:
      model = Person
      fields = ('name', 'birthdate', 'country', 'city')

   def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

class TaskCreateForm(forms.Form):
    cutting = forms.BooleanField(label='Cięcie piłą', required=False)
    insulating = forms.BooleanField(label='Izomowanie', required=False)
    gaskets = forms.BooleanField(label='Gumownia', required=False)
    frames = forms.BooleanField(label='Montaż ramy', required=False)
    vents = forms.BooleanField(label='Montaż skrzydeł', required=False)
    glass_frames = forms.BooleanField(label='Szklenie ramy', required=False)
    glass_vents = forms.BooleanField(label='Szklenie skrzydeł', required=False)

class ChociceTaskForm(forms.Form):
    processes = [
        ('Cut', 'Cutting'),
        ('Mill', 'Milling'),
        ('Mont', 'Montage')
    ]

    process_1 = forms.MultipleChoiceField(choices=processes)
    process_2 = forms.MultipleChoiceField(choices=processes)
         

ChainTest/ChainTest/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import render, redirect
from ChainTest.models import Person, City, Task, Order
from ChainTest.forms import PersonForm, TaskCreateForm

class PersonListView(ListView):
    model = Person
    context_object_name = 'people'

class PersonCreateView(CreateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')

class PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')

def load_cities(request):
   country_id = request.GET.get('country')
   cities = City.objects.filter(country_id=country_id).order_by('name')
   return render(request, 'hr/city_dropdown_list_options.html', {'cities': cities})

def form_handle(request, template_name = 'ChainTest/task_create.html'):
    form = TaskCreateForm()
    if request.method == 'POST':
        form = TaskCreateForm(request.POST)
        if form.is_valid():
            cdata = form.cleaned_data
            for k,v in cdata.items():
                if cdata[k] == True:
                    try:
                        Task.objects.create_task(k, Order.objects.get(id=1))
                    except:
                        form.add_error(None, 'Duplicated task: '+ k +' - please try again')
                        return render(request, template_name, {'form': form})
            return redirect('person_changelist')
    return render(request, template_name, {'form': form})

ChainTest/ChainTest/templates/ChainTest/person_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Person Form</h2>
  <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view (pobierz atrybut - data-cities-url - jest w template)
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

ChainTest/ChainTest/templates/ChainTest/person_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Person Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
        {% for person in people %}
          <li>{{ person.name }}</li>
        {% endfor %}
    </table>
  <br/>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>
{% endblock %}

ChainTest/ChainTest/templates/ChainTest/task_create.html
<form action="{% url 'form_handle' %}" method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>

ChainTest/ChainTest/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Project</title>
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

ChainTest/ChainTest/templates/hr/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.id }}">{{ city.name }}</option>
{% endfor %}